overblog_graphql:
    definitions:
        schema:
            query: Query
            resolver_maps:
                - App\Resolver\Map
        mappings:
            types:
                -
                    type: graphql
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
