Category:
    type: object
    config:
        fields:
            id:
                type: ID
            name:
                type: String
            slug:
                type: String

CategoryCollection:
    type: object
    config:
        fields:
            categories: "[Category]"