Friendship:
    type: object
    config:
        fields:
            id:
                type: ID
            sender: "User"
            reciver: "User"
            status: Boolean

FriendshipCollection:
    type: object
    config:
        fields:
            friendship: "[Friendship]"
            total: Int

FriendshipInput:
    type: input-object
    config:
        fields:
            sender: Int
            reciver: Int