Mutation:
    type: object
    config:
        fields:
            createCategory:
                type: "Category"
                resolve: "@=mutation('createCategory', [args])"
                args:
                    category: "CategoryInput"
                    
            updateCategory:
                type: "Category"
                resolve: "@=mutation('updateCategory', [args])"
                args:
                    category: "CategoryInput"
                    id: ID!

            deleteCategory:
                type: Int
                resolve: "@=mutation('deleteCategory', [args])"
                args:
                    id: ID!

            createGame:
                type: "Game"
                resolve: "@=mutation('createGame', [args])"
                args:
                    game: "GameInput"
                    
            updateGame:
                type: "Game"
                resolve: "@=mutation('updateGame', [args])"
                args:
                    game: "GameInput"
                    id: ID!

            deleteGame:
                type: Int
                resolve: "@=mutation('deleteGame', [args])"
                args:
                    id: ID!

            createUser:
                type: "User"
                resolve: "@=mutation('createUser', [args])"
                args:
                    user: "UserInput"
                    
            updateUser:
                type: "User"
                resolve: "@=mutation('updateUser', [args])"
                args:
                    user: "UserInput"
                    id: ID!

            deleteUser:
                type: Int
                resolve: "@=mutation('deleteUser', [args])"
                args:
                    id: ID!

            createRoom:
                type: "Room"
                resolve: "@=mutation('createRoom', [args])"
                args:
                    room: "RoomInput"
                    
            updateRoom:
                type: "Room"
                resolve: "@=mutation('updateRoom', [args])"
                args:
                    room: "RoomInput"
                    id: ID!

            deleteRoom:
                type: Int
                resolve: "@=mutation('deleteRoom', [args])"
                args:
                    id: ID!

            createPost:
                type: "Post"
                resolve: "@=mutation('createPost', [args])"
                args:
                    post: "PostInput"
                    
            updatePost:
                type: "Post"
                resolve: "@=mutation('updatePost', [args])"
                args:
                    post: "PostInput"
                    editor: ID!
                    id: ID!

            deletePost:
                type: Int
                resolve: "@=mutation('deletePost', [args])"
                args:
                    id: ID!
                    editor: ID!

            createComment:
                type: "Comment"
                resolve: "@=mutation('createComment', [args])"
                args:
                    comment: "CommentInput"
                    
            updateComment:
                type: "Comment"
                resolve: "@=mutation('updateComment', [args])"
                args:
                    comment: "CommentInput"
                    editor: ID!
                    id: ID!

            deleteComment:
                type: Int
                resolve: "@=mutation('deleteComment', [args])"
                args:
                    id: ID!
                    editor: ID!
            
            createFriendship:
                type: "Friendship"
                resolve: "@=mutation('createFriendship', [args])"
                args:
                    friendship: "FriendshipInput"

            deleteFriendship:
                type: Int
                resolve: "@=mutation('deleteFriendship', [args])"
                args:
                    id: ID!

            acceptFriendship:
                type: "Friendship"
                resolve: "@=mutation('acceptFriendship', [args])"
                args:
                    id: ID!

            login:
                access: "@=!isAuthenticated()"
                type: "String"
                resolve: "@=mutation('login', [args])"
                args:
                    password: String
                    userName: String

            setRole:
  #              access: "@=service('security.authorization_checker').isGranted('ROLE_ADMIN', 'ROLE_SUPER_ADMIN')"
                type: Boolean
                resolve: "@=mutation('setRole', [args])"
                args:
                    id: ID!
                    role: String!

#            createPostLike:
 #               type: "PostLike"
  #              resolve: "@=mutation('createPostLike', [args])"
   #             args:
    #                postLike: "PostLikeInput"

     #       deletePostLike:
      #          type: Int
       #         resolve: "@=mutation('deletePostLike', [args])"
        #        args:
         #           id: ID!
          #          editor: ID!

           # createCommentLike:
            #    type: "CommentLike"
             #   resolve: "@=mutation('createCommentLike', [args])"
              #  args:
               #     commentLike: "CommentLikeInput"

#            deleteCommentLike:
 #               type: Int
  #              resolve: "@=mutation('deleteCommentLike', [args])"
   #             args:
    #                id: ID!
     #               editor: ID!
            PostLike:
                type: "PostLike"
                resolve: "@=mutation('PostLike', [args])"
                args:
                    postLike: "PostLikeInput"