Mutation:
    type: object
    config:
        fields:
            createCategory:
                type: "Category"
                resolve: "@=mutation('createCategory', [args])"
                args:
                    category: "CategoryInput"
                    
            updateCategory:
                type: "Category"
                resolve: "@=mutation('updateCategory', [args])"
                args:
                    category: "CategoryInput"
                    id: ID!

            deleteCategory:
                type: "Category"
                resolve: "@=mutation('deleteCategory', [args])"
                args:
                    id: ID!

            createGame:
                type: "Game"
                resolve: "@=mutation('createGames', [args])"
                args:
                    game: "GameInput"
                    
            updateGame:
                type: "Game"
                resolve: "@=mutation('updateGames', [args])"
                args:
                    game: "GameInput"
                    id: ID!

            deleteGame:
                type: "Game"
                resolve: "@=mutation('deleteGames', [args])"
                args:
                    id: ID!