Mutation:
    type: object
    config:
        fields:
            createCategory:
                type: "Category"
                resolve: "@=mutation('createCategory', [args])"
                args:
                    category: "CategoryInput"
                    
            updateCategory:
                type: "Category"
                resolve: "@=mutation('updateCategory', [args])"
                args:
                    category: "CategoryInput"
                    id: ID!

            deleteCategory:
                type: Int
                resolve: "@=mutation('deleteCategory', [args])"
                args:
                    id: ID!

            createGame:
                type: "Game"
                resolve: "@=mutation('createGame', [args])"
                args:
                    game: "GameInput"
                    
            updateGame:
                type: "Game"
                resolve: "@=mutation('updateGame', [args])"
                args:
                    game: "GameInput"
                    id: ID!

            deleteGame:
                type: Int
                resolve: "@=mutation('deleteGame', [args])"
                args:
                    id: ID!

            createUser:
                type: "User"
                resolve: "@=mutation('createUser', [args])"
                args:
                    user: "UserInput"
                    
            updateUser:
                type: "User"
                resolve: "@=mutation('updateUser', [args])"
                args:
                    user: "UserInput"
                    id: ID!

            deleteUser:
                type: Int
                resolve: "@=mutation('deleteUser', [args])"
                args:
                    id: ID!

            createRoom:
                type: "Room"
                resolve: "@=mutation('createRoom', [args])"
                args:
                    room: "RoomInput"
                    
            updateRoom:
                type: "Room"
                resolve: "@=mutation('updateRoom', [args])"
                args:
                    room: "RoomInput"
                    id: ID!

            deleteRoom:
                type: Int
                resolve: "@=mutation('deleteRoom', [args])"
                args:
                    id: ID!

            createPost:
                type: "Post"
                resolve: "@=mutation('createPost', [args])"
                args:
                    post: "PostInput"
                    
            updatePost:
                type: "Post"
                resolve: "@=mutation('updatePost', [args])"
                args:
                    post: "PostInput"
                    id: ID!

            deletePost:
                type: Int
                resolve: "@=mutation('deletePost', [args])"
                args:
                    id: ID!

            createComment:
                type: "Comment"
                resolve: "@=mutation('createComment', [args])"
                args:
                    comment: "CommentInput"
                    
            updateComment:
                type: "Comment"
                resolve: "@=mutation('updateComment', [args])"
                args:
                    comment: "CommentInput"
                    id: ID!

            deleteComment:
                type: Int
                resolve: "@=mutation('deleteComment', [args])"
                args:
                    id: ID!
            
            createFriendship:
                type: "Friendship"
                resolve: "@=mutation('createFriendship', [args])"
                args:
                    friendship: "FriendshipInput"

            deleteFriendship:
                type: Int
                resolve: "@=mutation('deleteFriendship', [args])"
                args:
                    id: ID!

            login:
                type: "String"
                resolve: "@=mutation('login', [args])"
                args:
                    password: String
                    userName: String