Mutation:
    type: object
    config:
        fields:
            createCategory:
                type: "Category"
                resolve: "@=mutation('createCategory', [args])"
                args:
                    category: "CategoryInput"
                    
            updateCategory:
                type: "Category"
                resolve: "@=mutation('updateCategory', [args])"
                args:
                    category: "CategoryInput"