Query:
    type: object
    config:
        fields:
            category:
                type: Category
                args:
                    id:
                        type: ID
                resolve: "@=resolver('Category', [args])"

            allCategories:
                type: CategoryCollection
                args:
                    limit:
                        type: Int
                    name:
                        type: String
                    page:
                        type: Int
                    column:
                        type: String
                resolve: "@=resolver('allCategories', [args])"

            game:
                type: Game
                args:
                    id:
                        type: ID
                resolve: "@=resolver('Game', [args])"
                
            allGames:
                type: GameCollection
                args:
                    limit:
                        type: Int
                    name:
                        type: String
                    page:
                        type: Int
                    column:
                        type: String
                resolve: "@=resolver('allGames', [args])"
            
            user:
                type: User
                args:
                    id:
                        type: ID
                resolve: "@=resolver('User', [args])"
                
            allUsers:
                type: UserCollection
                args:
                    room: Int
                    limit:
                        type: Int
                    name:
                        type: String
                    page:
                        type: Int
                    column:
                        type: String
                resolve: "@=resolver('allUsers', [args])"

            room:
                type: Room
                args:
                    id:
                        type: ID
                resolve: "@=resolver('Room', [args])"
                
            allRooms:
                type: RoomCollection
                args:
                    limit:
                        type: Int
                    name:
                        type: String
                    page:
                        type: Int
                    column:
                        type: String
                resolve: "@=resolver('allRooms', [args])"

            post:
                type: Post
                args:
                    id:
                        type: ID
                resolve: "@=resolver('Post', [args])"
    
            allPosts:
                type: PostCollection
                args:
                    limit:
                        type: Int
                    title:
                        type: String
                    poster:
                        type: Int
                    page:
                        type: Int
                resolve: "@=resolver('allPosts', [args])"

            Comment:
                type: Comment
                args:
                    id:
                        type: ID
                resolve: "@=resolver('Comment', [args])"
                
            allComments:
                type: CommentCollection
                args:
                    limit:
                        type: Int
                    poster:
                        type: Int
                    post:
                        type: Int
                    page:
                        type: Int
                    column:
                        type: String
                resolve: "@=resolver('allComments', [args])"

            friendship:
                type: Friendship
                args:
                    id:
                        type: ID
                resolve: "@=resolver('Friendship', [args])"
                
            allFriendships:
                type: FriendshipCollection
                args:
                    limit:
                        type: Int
                    user: 
                        type: Int
                    page:
                        type: Int
                    column:
                        type: String
                resolve: "@=resolver('allFriendships', [args])"