Query:
    type: object
    config:
        fields:
            category:
                type: Category
                args:
                    id:
                        type: ID
                resolve: "@=resolver('Category', [args])"

            allCategories:
                type: CategoryCollection
                args:
                    limit:
                        type: Int
                    name:
                        type: String
                    page:
                        type: Int
                    column:
                        type: String
                resolve: "@=resolver('allCategories', [args])"

            game:
                type: Game
                args:
                    id:
                        type: ID
                resolve: "@=resolver('Game', [args])"
                
            allGames:
                type: GameCollection
                args:
                    limit:
                        type: Int
                    name:
                        type: String
                    page:
                        type: Int
                    column:
                        type: String
                resolve: "@=resolver('allGames', [args])"