Query:
    type: object
    config:
        fields:
            category:
                type: Category
                args:
                    id:
                        type: ID
                resolve: "@=resolver('Category', [args])"

            allCategories:
                type: CategoryCollection
                args:
                    limit:
                        type: Int
                    name:
                        type: String
                    page:
                        type: Int
                    column:
                        type: String
                resolve: "@=resolver('allCategories', [args])"

            game:
                type: Game
                args:
                    id:
                        type: ID
                resolve: "@=resolver('Game', [args])"
                
            allGames:
                type: GameCollection
                args:
                    limit:
                        type: Int
                    name:
                        type: String
                    page:
                        type: Int
                    column:
                        type: String
                resolve: "@=resolver('allGames', [args])"
            
            user:
                type: User
                args:
                    id:
                        type: ID
                resolve: "@=resolver('User', [args])"
                
            allUsers:
                type: UserCollection
                args:
                    room: Int
                    limit:
                        type: Int
                    name:
                        type: String
                    page:
                        type: Int
                    column:
                        type: String
                resolve: "@=resolver('allUsers', [args])"

            room:
                type: Room
                args:
                    id:
                        type: ID
                resolve: "@=resolver('Room', [args])"
                
            allRooms:
                type: RoomCollection
                args:
                    limit:
                        type: Int
                    name:
                        type: String
                    page:
                        type: Int
                    column:
                        type: String
                resolve: "@=resolver('allRooms', [args])"