Query:
    type: object
    config:
        fields:
            category:
                type: Category
                args:
                    id:
                        type: ID
                resolve: "@=resolver('Category', [args])"
            allCategories:
                type: CategoryCollection
                args:
                    limit:
                        type: Int
                    name:
                        type: String
                resolve: "@=resolver('allCategories', [args])"