Room:
    type: object
    config:
        fields:
            id:
                type: ID
            slug:
                type: String
            game: "Game"
            name: String
            isPrivate: Boolean
RoomCollection:
    type: object
    config:
        fields:
            rooms: "[Room]"
            total: Int

RoomInput:
    type: input-object
    config:
        fields:
            game: Int
            isPrivate: Boolean
            name: String

MessageCollection:
    type: object
    config:
        fields:
            messages: "[Message]"
            total: Int
            room: "Room"
Message:
    type: object
    config:
        fields:
            sender: "User"
            date: String
            content: String